name: Creates a new release when a tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  create-release-for-tag:
    name: "Create a release for the tag"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update version.py and remove unnecessary files
        run: |
          echo "pokebot_name = \"PokéBot\"" > modules/version.py
          echo "pokebot_version = \"${GITHUB_REF#refs/*/}\"" >> modules/version.py
          rm -rf .git .github .gitattributes .gitignore pokebot.spec
          mv LICENSE LICENSE.txt

      - name: Create a ZIP file
        run: |
          zip -qq -r /tmp/pokebot-${GITHUB_REF#refs/*/}.zip .

      - name: Creates the GitHub release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ $github.ref }}
          files: |
            /tmp/pokebot-${GITHUB_REF#refs/*/}.zip
